import type { Metadata } from "next";
import "../globals.css";
import { FC, use } from "react";
import { Locale, localeConfig } from "@/localization/config";
import { LocaleProvider } from "@/components/providers/LocaleProvider";
import { getDictionary } from "@/localization/dictiionary";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode
  params:Promise<{locale:Locale}>
}>

const RootLayout: FC<RootLayoutProps> = ({ children, params }) => {
  const locale = use(params).locale

  const dictionary = use(getDictionary(locale))

  return (
    <html lang="en">
      <body>
        <LocaleProvider dictionary={dictionary}>
          {children}
        </LocaleProvider>
      </body>
    </html>
  );
}

export default RootLayout


export const generateStaticParams = async () => {
  const locales = localeConfig.locales
  return locales.map((locale) => ({ locale }))
} 