import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { FC, use } from "react";
import { Locale, localeConfig } from "@/localization/config";
import { LocaleProvider } from "@/components/providers/LocaleProvider";
import { getDictionary } from "@/localization/dictionary";
import Sidebar from "@/components/shared/sidebar";


const inter = Inter({ subsets: ["latin"] });


type RootLayoutProps = Readonly<{
  children: React.ReactNode
  params:Promise<{locale:Locale}>
}>

const RootLayout: FC<RootLayoutProps> = ({ children, params }) => {
  const locale = use(params).locale
  const dictionary = use(getDictionary(locale))

  return (
    <html lang="en">
      <body className={inter.className}>
        <LocaleProvider dictionary={dictionary}>
          {children}
          <Sidebar locale={locale}/>
        </LocaleProvider>
      </body>
    </html>
  );
}

export default RootLayout


export const generateStaticParams = async () => {
  const locales = localeConfig.locales
  return locales.map((locale) => ({ locale }))
} 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
